const tierData = {
  maps: [
    {
      locationId: 2,
      tiers: [
        {
          tierName: '-Not Assigned-',
          nodes: [
            {
              itemId: 3270,
              itemName: 'LSI-ARRAY5',
              make: 'LSI',
              modelId: 1209,
              model: 'E3900',
              className: 'Network',
              status: 'Installed',
              cabinet: 'S33',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'Chassis',
              imageFront: false,
              imageRear: true,
            },
            {
              itemId: 3274,
              itemName: 'LSI-ARRAY9',
              make: 'LSI',
              modelId: 1209,
              model: 'E3900',
              className: 'Network',
              status: 'Installed',
              cabinet: 'S33',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'Chassis',
              imageFront: false,
              imageRear: true,
            },
            {
              itemId: 3839,
              itemName: 'USROS-CYC1-4I-01',
              make: 'Avocent',
              modelId: 1238,
              model: 'TS2000',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N04',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: false,
              imageRear: true,
            },
            {
              itemId: 3841,
              itemName: 'USROS-CYC2-4I-01',
              make: 'Avocent',
              modelId: 1238,
              model: 'TS2000',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N04',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: false,
              imageRear: true,
            },
            {
              itemId: 3843,
              itemName: 'USROS-CYC3-4I-01',
              make: 'Avocent',
              modelId: 1238,
              model: 'TS2000',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N04',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: false,
              imageRear: true,
            },
            {
              itemId: 3848,
              itemName: 'USROSI-01',
              make: 'MRV Communications',
              modelId: 1236,
              model: 'InReach',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N08',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: false,
              imageRear: false,
            },
            {
              itemId: 3849,
              itemName: 'USROSI-02',
              make: 'MRV Communications',
              modelId: 1236,
              model: 'InReach',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N08',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: false,
              imageRear: false,
            },
            {
              itemId: 3853,
              itemName: 'USROSRM1-BOTT3-01',
              make: 'Adtran',
              modelId: 1245,
              model: 'T3SU 300',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N08',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: false,
              imageRear: true,
            },
            {
              itemId: 3854,
              itemName: 'USROSRM1-INTT3-01',
              make: 'Adtran',
              modelId: 1245,
              model: 'T3SU 300',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N08',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: false,
              imageRear: true,
            },
            {
              itemId: 3855,
              itemName: 'USROSRM1-TCPT3-01',
              make: 'Adtran',
              modelId: 1245,
              model: 'T3SU 300',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N08',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: false,
              imageRear: true,
            },
            {
              itemId: 3856,
              itemName: 'USROSRM1-WHST3-01',
              make: 'Adtran',
              modelId: 1245,
              model: 'T3SU 300',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N08',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: false,
              imageRear: true,
            },
            {
              itemId: 3863,
              itemName: 'NJRAMS13-4I-SCR1',
              make: 'Foundry',
              modelId: 1302,
              model: 'Fast Iron JetCore 8-port mini-GBIC Gig',
              className: 'Network',
              status: 'Installed',
              cabinet: 'N05',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'Blade',
              imageFront: true,
              imageRear: false,
            },
            {
              itemId: 3885,
              itemName: 'USROSS16-4I-SCR-01',
              make: 'Nortel Networks',
              modelId: 1206,
              model: 'Switch 5510-24T',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N01',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: false,
            },
            {
              itemId: 3895,
              itemName: 'USROSS1-R57-SVR-01',
              make: 'Cisco Systems',
              modelId: 478,
              model: 'Catalyst C3750G-24T',
              className: 'Network',
              status: 'Installed',
              cabinet: 'S57',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: true,
            },
            {
              itemId: 3896,
              itemName: 'USROSS1-R64-SVR-01',
              make: 'Cisco Systems',
              modelId: 478,
              model: 'Catalyst C3750G-24T',
              className: 'Network',
              status: 'Installed',
              cabinet: 'S64',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: true,
            },
            {
              itemId: 3898,
              itemName: 'USROSS1-R73-SVR-01',
              make: 'Cisco Systems',
              modelId: 478,
              model: 'Catalyst C3750G-24T',
              className: 'Network',
              status: 'Installed',
              cabinet: 'S73',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: true,
            },
            {
              itemId: 3900,
              itemName: 'USROSS1-R83-SVR-01',
              make: 'Cisco Systems',
              modelId: 478,
              model: 'Catalyst C3750G-24T',
              className: 'Network',
              status: 'Installed',
              cabinet: 'S83',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: true,
            },
            {
              itemId: 3901,
              itemName: 'USROSS1-R86-SVR-01',
              make: 'Cisco Systems',
              modelId: 478,
              model: 'Catalyst C3750G-24T',
              className: 'Network',
              status: 'Installed',
              cabinet: 'S86',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: true,
            },
            {
              itemId: 3924,
              itemName: 'USROSS4-4I-SCR-01',
              make: 'Cisco Systems',
              modelId: 452,
              model: 'Catalyst C3750G-24TS',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N03',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: true,
            },
            {
              itemId: 3925,
              itemName: 'USROSS4-4I-SCR-02',
              make: 'Cisco Systems',
              modelId: 452,
              model: 'Catalyst C3750G-24TS',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N03',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: true,
            },
            {
              itemId: 3926,
              itemName: 'USROSS4-4I-SCR-03',
              make: 'Cisco Systems',
              modelId: 478,
              model: 'Catalyst C3750G-24T',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N03',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: true,
            },
            {
              itemId: 3927,
              itemName: 'USROSS4-4I-SCR-04',
              make: 'Cisco Systems',
              modelId: 478,
              model: 'Catalyst C3750G-24T',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N03',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: true,
            },
            {
              itemId: 3934,
              itemName: 'USROSS5-4I-SCR-01',
              make: 'Cisco Systems',
              modelId: 452,
              model: 'Catalyst C3750G-24TS',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N04',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: true,
            },
            {
              itemId: 3938,
              itemName: 'USROSS6-4I-SCR-01',
              make: 'Cisco Systems',
              modelId: 452,
              model: 'Catalyst C3750G-24TS',
              className: 'Network',
              status: 'Planned',
              cabinet: 'N04',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: true,
            },
            {
              itemId: 3942,
              itemName: 'USSEDESS00-01',
              make: 'Brocade',
              modelId: 33,
              model: 'Silkworm 3800',
              className: 'Network',
              status: 'Installed',
              cabinet: 'N15',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: false,
            },
            {
              itemId: 3943,
              itemName: 'USSEDESS00-02',
              make: 'Brocade',
              modelId: 33,
              model: 'Silkworm 3800',
              className: 'Network',
              status: 'Installed',
              cabinet: 'N15',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: false,
            },
            {
              itemId: 3944,
              itemName: 'USSEDESS00-03',
              make: 'Brocade',
              modelId: 33,
              model: 'Silkworm 3800',
              className: 'Network',
              status: 'Installed',
              cabinet: 'N15',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: false,
            },
            {
              itemId: 3945,
              itemName: 'USSEDESS00-04',
              make: 'Brocade',
              modelId: 33,
              model: 'Silkworm 3800',
              className: 'Network',
              status: 'Installed',
              cabinet: 'N15',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: false,
            },
            {
              itemId: 3946,
              itemName: 'USSEDESS00-05',
              make: 'Brocade',
              modelId: 33,
              model: 'Silkworm 3800',
              className: 'Network',
              status: 'Installed',
              cabinet: 'N15',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: false,
            },
            {
              itemId: 3947,
              itemName: 'USSEDESS00-06',
              make: 'Brocade',
              modelId: 33,
              model: 'Silkworm 3800',
              className: 'Network',
              status: 'Installed',
              cabinet: 'N15',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: false,
            },
            {
              itemId: 3948,
              itemName: 'USSEDESS00-07',
              make: 'Brocade',
              modelId: 33,
              model: 'Silkworm 3800',
              className: 'Network',
              status: 'Installed',
              cabinet: 'N15',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: false,
            },
            {
              itemId: 3949,
              itemName: 'USSEDESS00-08',
              make: 'Brocade',
              modelId: 33,
              model: 'Silkworm 3800',
              className: 'Network',
              status: 'Installed',
              cabinet: 'N15',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: false,
            },
            {
              itemId: 15109,
              itemName: 'MIC-AGGR-1',
              make: 'Arista Networks',
              modelId: 28138,
              model: 'DCS-7150S-24-F',
              className: 'Network',
              status: 'Planned',
              cabinet: 'S46',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: true,
            },
            {
              itemId: 15186,
              itemName: 'MIC-SWITCH-S46',
              make: 'Cisco Systems',
              modelId: 28038,
              model: 'Catalyst C3560-12P',
              className: 'Network',
              status: 'Planned',
              cabinet: 'S46',
              locationId: 2,
              location: 'SITE B',
              subClassName: 'NetworkStack',
              imageFront: true,
              imageRear: true,
            },
          ],
        },
      ],
    },
  ],
  links: [
    {
      sourceItemId: 3270,
      sourceItemName: 'LSI-ARRAY5',
      destItemId: 3946,
      destItemName: 'USSEDESS00-05',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 11150, sourcePortId: 33335, sourcePortName: 'CH1-TOP', destPortId: 39134, destPortName: 'P01' }],
    },
    {
      sourceItemId: 3270,
      sourceItemName: 'LSI-ARRAY5',
      destItemId: 3947,
      destItemName: 'USSEDESS00-06',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 11138, sourcePortId: 33334, sourcePortName: 'CH1-Bottom', destPortId: 39151, destPortName: 'P01' }],
    },
    {
      sourceItemId: 3274,
      sourceItemName: 'LSI-ARRAY9',
      destItemId: 3946,
      destItemName: 'USSEDESS00-05',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 11718, sourcePortId: 33351, sourcePortName: 'CH1-TOP', destPortId: 39148, destPortName: 'P15' }],
    },
    {
      sourceItemId: 3274,
      sourceItemName: 'LSI-ARRAY9',
      destItemId: 3947,
      destItemName: 'USSEDESS00-06',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 11722, sourcePortId: 33350, sourcePortName: 'CH1-Bottom', destPortId: 39165, destPortName: 'P15' }],
    },
    {
      sourceItemId: 3839,
      sourceItemName: 'USROS-CYC1-4I-01',
      destItemId: 3934,
      destItemName: 'USROSS5-4I-SCR-01',
      numOfHop: 0,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7923, sourcePortId: 36681, sourcePortName: 'C7-S1-P33', destPortId: 38868, destPortName: 'C5-S1-P01' }],
    },
    {
      sourceItemId: 3841,
      sourceItemName: 'USROS-CYC2-4I-01',
      destItemId: 3938,
      destItemName: 'USROSS6-4I-SCR-01',
      numOfHop: 0,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7919, sourcePortId: 36747, sourcePortName: 'C7-S2-P33', destPortId: 38989, destPortName: 'C6-S1-P24' }],
    },
    {
      sourceItemId: 3843,
      sourceItemName: 'USROS-CYC3-4I-01',
      destItemId: 3924,
      destItemName: 'USROSS4-4I-SCR-01',
      numOfHop: 0,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7921, sourcePortId: 36813, sourcePortName: 'C7-S3-P33', destPortId: 38633, destPortName: 'C4-S1-P08' }],
    },
    {
      sourceItemId: 3848,
      sourceItemName: 'USROSI-01',
      destItemId: 3924,
      destItemName: 'USROSS4-4I-SCR-01',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7941, sourcePortId: 36946, sourcePortName: 'Mgt', destPortId: 38630, destPortName: 'C4-S1-P05' }],
    },
    {
      sourceItemId: 3849,
      sourceItemName: 'USROSI-02',
      destItemId: 3924,
      destItemName: 'USROSS4-4I-SCR-01',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7945, sourcePortId: 36955, sourcePortName: 'Mgt', destPortId: 38631, destPortName: 'C4-S1-P06' }],
    },
    {
      sourceItemId: 3853,
      sourceItemName: 'USROSRM1-BOTT3-01',
      destItemId: 3924,
      destItemName: 'USROSS4-4I-SCR-01',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7933, sourcePortId: 36974, sourcePortName: 'Mgt', destPortId: 38628, destPortName: 'C4-S1-P03' }],
    },
    {
      sourceItemId: 3854,
      sourceItemName: 'USROSRM1-INTT3-01',
      destItemId: 3924,
      destItemName: 'USROSS4-4I-SCR-01',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7937, sourcePortId: 36975, sourcePortName: 'Mgt', destPortId: 38629, destPortName: 'C4-S1-P04' }],
    },
    {
      sourceItemId: 3855,
      sourceItemName: 'USROSRM1-TCPT3-01',
      destItemId: 3924,
      destItemName: 'USROSS4-4I-SCR-01',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7929, sourcePortId: 36976, sourcePortName: 'Mgt', destPortId: 38627, destPortName: 'C4-S1-P02' }],
    },
    {
      sourceItemId: 3856,
      sourceItemName: 'USROSRM1-WHST3-01',
      destItemId: 3924,
      destItemName: 'USROSS4-4I-SCR-01',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7925, sourcePortId: 36977, sourcePortName: 'Mgt', destPortId: 38626, destPortName: 'C4-S1-P01' }],
    },
    {
      sourceItemId: 3885,
      sourceItemName: 'USROSS16-4I-SCR-01',
      destItemId: 3863,
      destItemName: 'NJRAMS13-4I-SCR1',
      numOfHop: 0,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 11000, sourcePortId: 37730, sourcePortName: 'C16-S1-P24', destPortId: 37104, destPortName: 'C13-S1-P07' }],
    },
    {
      sourceItemId: 3895,
      sourceItemName: 'USROSS1-R57-SVR-01',
      destItemId: 3938,
      destItemName: 'USROSS6-4I-SCR-01',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 10504, sourcePortId: 37970, sourcePortName: 'C1-S1-P24', destPortId: 38966, destPortName: 'C6-S1-P01' }],
    },
    {
      sourceItemId: 3896,
      sourceItemName: 'USROSS1-R64-SVR-01',
      destItemId: 3938,
      destItemName: 'USROSS6-4I-SCR-01',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 10520, sourcePortId: 37994, sourcePortName: 'C1-S1-P24', destPortId: 38972, destPortName: 'C6-S1-P07' }],
    },
    {
      sourceItemId: 3898,
      sourceItemName: 'USROSS1-R73-SVR-01',
      destItemId: 3938,
      destItemName: 'USROSS6-4I-SCR-01',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 10508, sourcePortId: 38035, sourcePortName: 'C1-S1-P24', destPortId: 38967, destPortName: 'C6-S1-P02' }],
    },
    {
      sourceItemId: 3900,
      sourceItemName: 'USROSS1-R83-SVR-01',
      destItemId: 3938,
      destItemName: 'USROSS6-4I-SCR-01',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 10512, sourcePortId: 38083, sourcePortName: 'C1-S1-P24', destPortId: 38970, destPortName: 'C6-S1-P05' }],
    },
    {
      sourceItemId: 3901,
      sourceItemName: 'USROSS1-R86-SVR-01',
      destItemId: 3938,
      destItemName: 'USROSS6-4I-SCR-01',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 10516, sourcePortId: 38107, sourcePortName: 'C1-S1-P24', destPortId: 38971, destPortName: 'C6-S1-P06' }],
    },
    {
      sourceItemId: 3942,
      sourceItemName: 'USSEDESS00-01',
      destItemId: 3924,
      destItemName: 'USROSS4-4I-SCR-01',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7302, sourcePortId: 39064, sourcePortName: 'Mgr', destPortId: 38648, destPortName: 'C4-S1-P23' }],
    },
    {
      sourceItemId: 3943,
      sourceItemName: 'USSEDESS00-02',
      destItemId: 3925,
      destItemName: 'USROSS4-4I-SCR-02',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7306, sourcePortId: 39081, sourcePortName: 'Mgr', destPortId: 38654, destPortName: 'C4-S2-P04' }],
    },
    {
      sourceItemId: 3944,
      sourceItemName: 'USSEDESS00-03',
      destItemId: 3924,
      destItemName: 'USROSS4-4I-SCR-01',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7310, sourcePortId: 39098, sourcePortName: 'Mgr', destPortId: 38649, destPortName: 'C4-S1-P24' }],
    },
    {
      sourceItemId: 3945,
      sourceItemName: 'USSEDESS00-04',
      destItemId: 3925,
      destItemName: 'USROSS4-4I-SCR-02',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7314, sourcePortId: 39115, sourcePortName: 'Mgr', destPortId: 38655, destPortName: 'C4-S2-P05' }],
    },
    {
      sourceItemId: 3946,
      sourceItemName: 'USSEDESS00-05',
      destItemId: 3925,
      destItemName: 'USROSS4-4I-SCR-02',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7318, sourcePortId: 39132, sourcePortName: 'Mgr', destPortId: 38656, destPortName: 'C4-S2-P06' }],
    },
    {
      sourceItemId: 3947,
      sourceItemName: 'USSEDESS00-06',
      destItemId: 3926,
      destItemName: 'USROSS4-4I-SCR-03',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7322, sourcePortId: 39149, sourcePortName: 'Mgr', destPortId: 38678, destPortName: 'C4-S3-P03' }],
    },
    {
      sourceItemId: 3948,
      sourceItemName: 'USSEDESS00-07',
      destItemId: 3927,
      destItemName: 'USROSS4-4I-SCR-04',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7326, sourcePortId: 39166, sourcePortName: 'Mgr', destPortId: 38706, destPortName: 'C4-S4-P07' }],
    },
    {
      sourceItemId: 3949,
      sourceItemName: 'USSEDESS00-08',
      destItemId: 3927,
      destItemName: 'USROSS4-4I-SCR-04',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 7330, sourcePortId: 39183, sourcePortName: 'Mgr', destPortId: 38707, destPortName: 'C4-S4-P08' }],
    },
    {
      sourceItemId: 15186,
      sourceItemName: 'MIC-SWITCH-S46',
      destItemId: 15109,
      destItemName: 'MIC-AGGR-1',
      numOfHop: 1,
      numOfConnection: 1,
      circuitDetails: [{ circuitId: 12795, sourcePortId: 94182, sourcePortName: 'P14', destPortId: 94059, destPortName: 'P01' }],
    },
  ],
};
function processTier(apiData) {
  const nodes = [];
  const edges = [];
  apiData.maps.forEach((map) => {
    map.tiers.forEach((tier) => {
      tier.nodes.forEach((node) => {
        node.id = node.itemId + '';
        nodes.push({ data: node });
      });
    });
  });
  apiData.links.forEach((link) => {
    link.source = link.sourceItemId + '';
    link.target = link.destItemId + '';
    link.id = `${link.source}_${link.target}`;
    edges.push({ data: link });
  });
  return { nodes, edges };
}
export const tier1 = processTier(tierData);

const meshData = {
  groups: [
    {
      nodes: [
        {
          itemId: 4865,
          itemName: 'WS-PH-10',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-110',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
        {
          itemId: 4866,
          itemName: 'WS-PH-11',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-111',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
        {
          itemId: 4867,
          itemName: 'WS-PH-12',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-112',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
        {
          itemId: 4868,
          itemName: 'WS-PH-13',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-113',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
        {
          itemId: 4873,
          itemName: 'VOIP-01-01',
          make: 'Cisco Systems',
          modelId: 479,
          model: 'Catalyst C3750E-48TD',
          className: 'Network',
          status: 'Installed',
          cabinet: 'R1',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'NetworkStack',
          imageFront: true,
          imageRear: true,
          leaf: false,
        },
        {
          itemId: 4842,
          itemName: 'WS-PH-01',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-101',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
        {
          itemId: 4856,
          itemName: 'WS-PH-02',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-102',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
        {
          itemId: 4857,
          itemName: 'WS-PH-03',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-103',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
        {
          itemId: 4858,
          itemName: 'WS-PH-14',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-114',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
        {
          itemId: 4859,
          itemName: 'WS-PH-04',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-104',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
        {
          itemId: 4860,
          itemName: 'WS-PH-05',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-105',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
        {
          itemId: 4861,
          itemName: 'WS-PH-06',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-106',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
        {
          itemId: 4862,
          itemName: 'WS-PH-07',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-107',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
        {
          itemId: 4863,
          itemName: 'WS-PH-09',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-109',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
        {
          itemId: 4864,
          itemName: 'WS-PH-08',
          make: 'Cisco Systems',
          modelId: 17817,
          model: 'VoIP Phone',
          className: 'Device',
          status: 'Installed',
          cabinet: 'WS-108',
          locationId: 6,
          location: 'SITE IDF',
          subClassName: 'Standard',
          imageFront: true,
          imageRear: true,
          leaf: true,
        },
      ],
      links: [
        {
          sourceItemId: 4842,
          sourceItemName: 'WS-PH-01',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11929, sourcePortId: 48170, sourcePortName: 'Eth01', destPortId: 48436, destPortName: 'P01' }],
        },
        {
          sourceItemId: 4868,
          sourceItemName: 'WS-PH-13',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11950, sourcePortId: 48196, sourcePortName: 'Eth01', destPortId: 48412, destPortName: 'P25' }],
        },
        {
          sourceItemId: 4867,
          sourceItemName: 'WS-PH-12',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11948, sourcePortId: 48195, sourcePortName: 'Eth01', destPortId: 48413, destPortName: 'P23' }],
        },
        {
          sourceItemId: 4864,
          sourceItemName: 'WS-PH-08',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11940, sourcePortId: 48192, sourcePortName: 'Eth01', destPortId: 48422, destPortName: 'P15' }],
        },
        {
          sourceItemId: 4863,
          sourceItemName: 'WS-PH-09',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11942, sourcePortId: 48191, sourcePortName: 'Eth01', destPortId: 48420, destPortName: 'P17' }],
        },
        {
          sourceItemId: 4866,
          sourceItemName: 'WS-PH-11',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11946, sourcePortId: 48194, sourcePortName: 'Eth01', destPortId: 48416, destPortName: 'P21' }],
        },
        {
          sourceItemId: 4865,
          sourceItemName: 'WS-PH-10',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11944, sourcePortId: 48193, sourcePortName: 'Eth01', destPortId: 48418, destPortName: 'P19' }],
        },
        {
          sourceItemId: 4860,
          sourceItemName: 'WS-PH-05',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11934, sourcePortId: 48188, sourcePortName: 'Eth01', destPortId: 48428, destPortName: 'P09' }],
        },
        {
          sourceItemId: 4859,
          sourceItemName: 'WS-PH-04',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11932, sourcePortId: 48187, sourcePortName: 'Eth01', destPortId: 48430, destPortName: 'P07' }],
        },
        {
          sourceItemId: 4862,
          sourceItemName: 'WS-PH-07',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11938, sourcePortId: 48190, sourcePortName: 'Eth01', destPortId: 48424, destPortName: 'P13' }],
        },
        {
          sourceItemId: 4861,
          sourceItemName: 'WS-PH-06',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11936, sourcePortId: 48189, sourcePortName: 'Eth01', destPortId: 48426, destPortName: 'P11' }],
        },
        {
          sourceItemId: 4856,
          sourceItemName: 'WS-PH-02',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11930, sourcePortId: 48184, sourcePortName: 'Eth01', destPortId: 48434, destPortName: 'P03' }],
        },
        {
          sourceItemId: 4858,
          sourceItemName: 'WS-PH-14',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11952, sourcePortId: 48186, sourcePortName: 'Eth01', destPortId: 48410, destPortName: 'P27' }],
        },
        {
          sourceItemId: 4857,
          sourceItemName: 'WS-PH-03',
          destItemId: 4873,
          destItemName: 'VOIP-01-01',
          numOfHop: 1,
          numOfConnection: 1,
          circuitDetails: [{ circuitId: 11928, sourcePortId: 48185, sourcePortName: 'Eth01', destPortId: 48432, destPortName: 'P05' }],
        },
      ],
    },
  ],
};
function processMesh(apiData) {
  const nodes = [];
  const edges = [];
  apiData.groups.forEach((group) => {
    group.nodes.forEach((node) => {
      node.id = node.itemId + '';
      nodes.push({ data: node });
    });
    group.links.forEach((link) => {
      link.source = link.sourceItemId + '';
      link.target = link.destItemId + '';
      link.id = `${link.source}_${link.target}`;
      edges.push({ data: link });
    });
  });
  return { nodes, edges };
}
export const mesh1 = processMesh(meshData);
